# Generated by Django 2.0.5 on 2018-05-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='spreadsheet_id',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='spreadsheet_url',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='trelloboard_id',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='trelloboard_url',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
