# Generated by Django 2.0.5 on 2018-05-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180527_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spreadsheet_id', models.CharField(default='', max_length=1000)),
                ('trelloboard_id', models.CharField(default='', max_length=1000)),
                ('spreadsheet_url', models.CharField(default='', max_length=1000)),
                ('trelloboard_url', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='spreadsheet_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='spreadsheet_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='trelloboard_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='trelloboard_url',
        ),
    ]
